### ISSUE TITLE
cant load plugin

### ISSUE THREAD

**Issue by a-a3458** [CrazyMoosen/Increasing-Item-Drops-Plugin#1]
I tried the plugin on 1.16.1 and it always comes up with saying can't load plugin in plugins folder

**Comment by CrazyMoosen** [comment]
can you tell me more, like what type server you started up, and how exactly you started up the server and if you had another plugin that messed around with the drop rate of the blocks

**Comment by a-a3458** [comment]
I was using server.pro on a 1.16.5 spigot server and it when I looked at
logs to said can’t load the plug-in

**Comment by CrazyMoosen** [comment]
Wait, so the version you ran it on was 1.16.5?

Also, do you mind telling me if there were any other plugins you are running?

**Comment by a-a3458** [comment]
yes ran it on 1.16.5 and i even tried it with no plugins it still said
couldn't load plugin

**Comment by CrazyMoosen** [comment]
Try uninstalling and installing the plugin again.

**Comment by CrazyMoosen** [comment]
Ok, I made my own Server.pro server to see what the problem is and the same thing happened to me. Luckily, I have a solution. Server.pro free servers only support Java Runtime v52.0, so I will upload a version of the plugin for Server.pro.
